Add agent name in logger paths
fetchai/agents-aea pull request #1786
Opened 2020-10-01 21:40 UTC by marcofavorito

## Proposed changes

Add agent name in logger paths

## Fixes

Fix #1568 

## Types of changes

What types of changes does your code introduce to agents-aea?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply._

- [ ] I have read the [CONTRIBUTING](../CONTRIBUTING.md) doc
- [ ] I am making a pull request against the `develop` branch (left side). Also you should start your branch off our `develop`.
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that code coverage does not decrease.
- [ ] I have checked that the documentation about the `aea cli` tool works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

n/a

2020-10-02 07:26 UTC, DavidMinarsch requested changes
LGTM, some comments and missing tests

2020-10-02 07:26 UTC, DavidMinarsch commented on aea/aea_builder.py
> +        resources = Resources()
Resources also needs to be fed the correct logger if I remember correctly

2020-10-07 15:40 UTC, DavidMinarsch commented on aea/aea.py
> -class AEA(Agent, WithLogger):
Agent also needs a logger, moved to Agent.

2020-10-07 15:40 UTC, DavidMinarsch commented on aea/aea_builder.py
> +_default_logger = logging.getLogger(__name__)
All per module loggers are now named `_default_logger` to avoid any ambiguities and have consistency across the code base!

2020-10-07 15:40 UTC, DavidMinarsch commented on aea/cli/generate.py
> +        warning_message = protocol_generator.generate()
Warning message should use click.echo not the logger when used from cli

2020-10-07 16:01 UTC, solarw approved these changes
lgtm

2020-10-07 19:12 UTC, DavidMinarsch approved these changes
LGTM

2020-10-08 15:49 UTC, merged