coincurve for cosmos ledger plugin
fetchai/agents-aea pull request #2430
Opened 2021-03-30 12:09 UTC by solarw

## Proposed changes

coincurve for cosmos ledger plugin

## Fixes

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] I have read the [CONTRIBUTING](../CONTRIBUTING.md) doc
- [x] I am making a pull request against the `develop` branch (left side). Also you should start your branch off our `develop`.
- [x] Lint and unit tests pass locally with my changes and CI passes too
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that code coverage does not decrease.
- [x] I have added necessary documentation (if appropriate)
- [x] Any dependent changes have been merged and published in downstream modules

2021-03-30 12:39 UTC, marcofavorito approved these changes
LGTM

2021-03-30 12:42 UTC, marcofavorito commented on Pipfile
> +coincurve = ">=15.0.0"
why here, if `coincurve` is in `setup.py`?

2021-03-30 12:53 UTC, DavidMinarsch requested changes
This currently does not play nicely with the ACN. We need to investigate why and resolve this before continuing with it.

2021-09-19 20:56 UTC, DavidMinarsch commented
Outdated - closing now

2021-09-19 20:56 UTC, closed without merging