fix: validate aea_version when loading configuration (#2519)
fetchai/agents-aea pull request #2551
Opened 2021-06-07 16:51 UTC by marcofavorito

## Proposed changes

Validate aea_version when loading configuration.

That is, before validating the loaded YAML file against the schema, first check that `aea_version` is consistent with the current `aea` version being used.

## Fixes

#2519

## Types of changes

What types of changes does your code introduce to agents-aea?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply._

- [ ] I have read the [CONTRIBUTING](../CONTRIBUTING.md) doc
- [ ] I am making a pull request against the `develop` branch (left side). Also you should start your branch off our `develop`.
- [ ] Lint and unit tests pass locally with my changes and CI passes too
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that code coverage does not decrease.
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

DELETE INCLUSIVE THIS AND BELOW FOR STANDARD PR
------

## Release summary

Version number: [e.g. 1.0.1]

## Release details

Describe in short the main changes with the new release.

## Checklist

_Put an `x` in the boxes that apply._

- [ ] I have read the [CONTRIBUTING](../CONTRIBUTING.md) doc
- [ ] I am making a pull request against the `main` branch (left side), from `develop`
- [ ] Lint and unit tests pass locally and in CI
- [ ] I have checked the fingerprint hashes are correct by running (`scripts/generate_ipfs_hashes.py`)
- [ ] I have regenerated the latest API docs
- [ ] I built the documentation and updated it with the latest changes
- [ ] I have added an item in `HISTORY.md` for this release
- [ ] I bumped the version number in the `aea/__version__.py` file.
- [ ] I bumped the version number in every Docker image of the repo and published it. Also, I built and published them with tag `latest`  
      (check the READMEs of [`aea-develop`](../develop-image/README.md#publish) 
      and [`aea-user`](../user-image/README.md#publish))
- [ ] I have pushed the latest packages to the registry.
- [ ] I have uploaded the latest `aea` to PyPI.
- [ ] I have uploaded the latest plugins to PyPI.

## Further comments

Write here any other comment about the release, if any.

2021-06-08 08:16 UTC, DavidMinarsch approved these changes
LGTM

2021-06-08 08:18 UTC, DavidMinarsch requested changes
Upgrade tests fail, we probably have to skip validation for packages which are about to be upgraded. We should also make it possible to fetch packages which are outdated, this should just not be possible on AEA manager, but should be possible on fetch. So I'd say the new validation logic added needs to be by default off and only on when we use it in manager.

2021-06-08 19:58 UTC, DavidMinarsch commented on aea/manager/project.py
> +        skip_aea_validation: bool = True,
why skip during load?

2021-06-08 20:06 UTC, marcofavorito commented on aea/manager/project.py
> +        skip_aea_validation: bool = True,
will put it to `False`

2021-06-08 20:07 UTC, marcofavorito commented on aea/manager/project.py
> +        skip_aea_validation: bool = True,
```suggestion
        skip_aea_validation: bool = False,
```

2021-06-09 09:22 UTC, DavidMinarsch approved these changes
LGTM

2021-06-09 09:28 UTC, solarw approved these changes
LGTM

2021-06-09 19:45 UTC, merged