Contract Test Tool
fetchai/agents-aea pull request #2576
Opened 2021-07-07 15:37 UTC by 5A11

This PR adds a contract test tool and applies it onto the existing ERC1155 contract package tests for Ethereum.

## Types of changes

What types of changes does your code introduce to agents-aea?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply._

- [x] I have read the [CONTRIBUTING](../CONTRIBUTING.md) doc
- [x] I am making a pull request against the `develop` branch (left side). Also you should start your branch off our `develop`.
- [x ] Lint and unit tests pass locally with my changes and CI passes too
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that code coverage does not decrease.
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

2021-07-09 08:39 UTC, solarw approved these changes
LGTM

2021-07-12 06:49 UTC, DavidMinarsch requested changes

2021-07-12 06:49 UTC, DavidMinarsch commented on aea/test_tools/test_contract.py
> +    @staticmethod
This should not be tied to Ethereum, it should accept an "identifier" and work for arbitrary ledgers.

2021-07-12 06:49 UTC, DavidMinarsch commented on aea/test_tools/test_contract.py
> +from aea_ledger_ethereum import EthereumCrypto
aea should not depend on plugins, that causes circularity

2021-07-17 09:59 UTC, DavidMinarsch reviewed
@5A11 I applied the required fixes to make it ledger independent. The next step would be to apply the same test class to `TestCosmWasmContract` in  `tests/test_packages/test_contracts/test_erc1155/test_contract.py`.

2021-07-26 08:35 UTC, DavidMinarsch approved these changes
LGTM

2021-08-01 17:09 UTC, merged