Stargate
fetchai/agents-aea pull request #2613
Opened 2021-09-06 08:21 UTC by 5A11

## Proposed changes

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request.

## Fixes

If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Types of changes

What types of changes does your code introduce to agents-aea?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply._

- [ ] I have read the [CONTRIBUTING](../CONTRIBUTING.md) doc
- [ ] I am making a pull request against the `develop` branch (left side). Also you should start your branch off our `develop`.
- [ ] Lint and unit tests pass locally with my changes and CI passes too
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that code coverage does not decrease.
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

DELETE INCLUSIVE THIS AND BELOW FOR STANDARD PR
------

## Release summary

Version number: [e.g. 1.0.1]

## Release details

Describe in short the main changes with the new release.

## Checklist

_Put an `x` in the boxes that apply._

- [ ] I have read the [CONTRIBUTING](../CONTRIBUTING.md) doc
- [ ] I am making a pull request against the `main` branch (left side), from `develop`
- [ ] Lint and unit tests pass locally and in CI
- [ ] I have checked the fingerprint hashes are correct by running (`scripts/generate_ipfs_hashes.py`)
- [ ] I have regenerated the latest API docs
- [ ] I built the documentation and updated it with the latest changes
- [ ] I have added an item in `HISTORY.md` for this release
- [ ] I bumped the version number in the `aea/__version__.py` file.
- [ ] I bumped the version number in every Docker image of the repo and published it. Also, I built and published them with tag `latest`  
      (check the READMEs of [`aea-develop`](../develop-image/README.md#publish) 
      and [`aea-user`](../user-image/README.md#publish))
- [ ] I have pushed the latest packages to the registry.
- [ ] I have uploaded the latest `aea` to PyPI.
- [ ] I have uploaded the latest plugins to PyPI.

## Further comments

Write here any other comment about the release, if any.

2021-09-06 13:39 UTC, panasevychol approved these changes

2021-09-06 16:53 UTC, jrriehl commented on packages/fetchai/agents/random_beacon_feed/aea-config.yaml
> -      address: https://rest-beaconworld.fetch.ai:443
I'll check on this, but I believe that Stargateworld does not have a random beacon.

2021-09-06 16:59 UTC, jrriehl approved these changes
Looks good

2021-09-06 20:52 UTC, DavidMinarsch requested changes
The idea was that the switch to stargate finally resolves the test failures. However, I observe quite a few and it is harder to see now where they come from. I suggest @solarw has a look to address them so that we have a green test run before we merge.

2021-09-07 08:25 UTC, 5A11 commented
> The idea was that the switch to stargate finally resolves the test failures. However, I observe quite a few and it is harder to see now where they come from. I suggest @solarw has a look to address them so that we have a green test run before we merge.

We have addressed all Stargate related failures. There is none in this PR. 
The failures are either:
a) public DHT related: waiting for prod to be synced with latest ACN changes.
b) multi aea manager related: @solarw is looking into those.
c) odd failures here and there: also @solarw is looking into those.

2021-09-07 09:51 UTC, merged